### ISSUE TITLE
As an EDP User, I want to onboard the helm chart application

### ISSUE THREAD

**Issue by Iryna-Churkina** [epam/edp-install#1]
Provide the ability to deploy additional services with the main applications as dependencies.
Provide base CI for helm charts, thus allowing user to select a service in the CD pipeline.

Acceptance Criteria:

- user can add codebases type helm via Headlamp;
- language: helm framework: helm and build tool: helm;
- create repo for create strategy;
- Tekton CI/CD (add review and build pipelines) pipelines available for helm charts;
- check deploy functional (user can add services and deploy as dependency for application);
- check EDP and default versioning approaches;
- publish helm chart with appropriate version to registry;
- add repos with tests sources to github and gitlab for import strategy;
- describe usage in documentation (https://epam.github.io/edp-install/);

As a test template, use the PostgreSQL DB or any other.

**Comment by YevheniiPokhvalii** [comment]
Closes: #1
