### ISSUE TITLE
Upgrade SolutionsHub

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#11]
Please collect the info for the Use Cases block in the SolutionsHub page.

Useful:

- Use cases sample from another product - https://solutionshub.epam.com/solution/deps
- our EDP page - https://solutionshub.epam.com/solution/epam-delivery-platform
- our use cases - https://epam.github.io/edp-install/use-cases/
- email thread - RE: [EPMD-EDP][SolutionsHub] Add Use Cases Section
- update features block
- update technical req
- update INTEGRATES with
- 

benefits:

- opensource;
- mkdocs framework (perfect docs)
- maybe active community

**Comment by SecretiveRabbit** [comment]
The SolutionsHub page has been aligned with the latest EDP 3.3.0 version.
https://solutionshub.epam.com/solution/epam-delivery-platform.

**Comment by SecretiveRabbit** [comment]
Close #11
