### ISSUE TITLE
As an EDP user I want to have opportunity deploy applications in to different clusters

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#14]
Acceptance Criteria:

* user can integrate EDP with different clusters;
* mkdocs contain article of how to use this feature;
* user can deploy each CD pipeline stage to different clusters;
* add 'clusters' section in Headlamp UI;
* provide opportunity to add new cluster;
* each EDP tenant must be deployed with Argo CD;
* align with current RBAC model;
* Argo CD mandatory parameter by default;
* git servers must be automatically integrated with Argo CD; (codeabsae-operator logic)
* user can be add new cluster via Argo CD or Headlamp UI;
* align mkdocs;
* ** align autotest run;
* ** align custom CG run;
* ** align custom logic run on CD part;

![Image](https://user-images.githubusercontent.com/37263265/237016417-c6e2d0d3-017a-4d50-8053-c22f18066dc0.png)

**Comment by Artem-Zahumonnyi** [comment]
We have implemented the ability to deploy applications in to different clusters via the Headlamp UI.
For this, a new Headlamp section has been added to work with clusters, that was named "Clusters". It is located in **EDP** -> **Configurations**

The new feature is described in our documentation on the ["Add Cluster"](https://epam.github.io/edp-install/headlamp-user-guide/add-cluster/) page.

![image](https://github.com/epam/edp-install/assets/51204821/b9fc60ee-4c08-4d93-98d9-4d4eda080248)
