### ISSUE TITLE
As an EDP user I want to integrate EDP solution with third-party SonarQube

### ISSUE THREAD

**Issue by MykolaMarusenko** [epam/edp-install#16]
Acceptance Criteria:

* user can disable default SonarQube and integrate with third-party SonarQube;
* user can create custom secret for integration EDP with SonarQube;
* EDP supports integration with custom SonarQube, a valid link in the EDP component, in Headlamp, Tekton pipelines are adapted to work with custom SonarQube;
* provide mk-docs (https://epam.github.io/edp-install/) tutorial of automate integration;

**Comment by alezander86** [comment]
We have successfully completed your request for integrating EDP solution with third-party SonarQube. Users can now disable the default SonarQube and integrate with third-party SonarQube. Additionally, users can create custom secrets for integrating EDP with SonarQube.

EDP now supports integration with custom SonarQube and includes a valid link in the EDP component, Headlamp, and adapted Tekton pipelines to work efficiently with custom SonarQube instances.

We have also provided detailed documentation on how to perform the integration, which you can find on [our EDP website](https://epam.github.io/edp-install/operator-guide/sonarqube/?h=sonar).

Please feel free to explore the tutorial, and if you have any further questions or need assistance, don't hesitate to ask.
