### ISSUE TITLE
Deploy Argo CD as EDP subcomponent

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#18]
In the current deployment scenario, the deployment of the ArgoCD component is used to provide functionality for the deployment of services, with this approach, a centralized ArgoCD with cluster admin permissions is used, this may not be available for part of the deployment scenarios and project requirements, it would be nice to be able to deploy ArgoCD as a subcomponent of the platform with the appropriate RBAC.

In addition, it would be nice to automate some of the integrations, such as integration with Keycloak for SSO access and integration with git servers out of the box.

Acceptance Criteria:

- edp-install contain ArgoCD as dependency;
- Argo CD deployed in namespace wide mode;
- automate EDP+ArgoCD integration;
- ArgoCD must be deployed with Keycloak integration;
- ArgoCD values must be production ready (investigate HA mode..);
- check CD pipeline works;
- Define ArgoCD project view;
- add EDP component with ArgoCD link;
- Upgrade mkdocs to new approach:
      https://epam.github.io/edp-install/operator-guide/install-argocd/?h=
      https://epam.github.io/edp-install/operator-guide/argocd-integration/

**Comment by SergK** [comment]
Partially implemented, no further automation is expected in the nearest time
