### ISSUE TITLE
As a User, I want to onboard next.js framework for JavaScript codebase

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#19]
It would be nice to be able to onboard the next js framework for JavaScript as part of the EDP platform - https://nextjs.org/

Acceptance Criteria:

- Update Headlamp UI to add oppotrunity to set nextjs framework for JavaScript;
- Enable 'create' strategy for this application type;
- Align Tekton Pipelines;
- Update mkdocs documentation - https://epam.github.io/edp-install/;

**Comment by YevheniiPokhvalii** [comment]
Next.js framework for JavaScript is supported by default in EDP.
Closes #19
