### ISSUE TITLE
As an EDP User, I want to use auto deploy in Headlamp and Argo CD deploy scenario

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#2]
Enable logic to provide autodeploy approach in Argo CD deploy scenario.

Each time when Build pipeline update CodebaseImageStream Custom Resource - define latest artifact tag and upgrade this service on each environment, where this service deployed.

In Headlamp UI in CD pipeline create dialog enable functional to create env with auto deploy approach.

**Comment by zmotso** [comment]
Now it is possible to use autodeploy approach in Argo CD scenario.
![image](https://github.com/epam/edp-install/assets/10484729/d5c903f2-ecb5-43f3-9b1a-f3a636329b18)
