### ISSUE TITLE
Publish GitHub open-source template to EDP GitHub repositories

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#20]
Currently EDP provide template for keycloak-operator - https://github.com/epam/edp-keycloak-operator/issues/new/choose

Lets add templates for all repositories this simplifies the creation of typical requests to the GitHub repositories

Acceptance Criteria:

- each EDP repositories contain GitHub open-source templates;

**Comment by Rolika4** [comment]
We have implemented several updates to improve communication and collaboration within our EDP subcomponents. 

These include the addition of a code of conduct, contributing rules, and templates for bug reports and feature requests. 

These templates can now be utilized to create issues that help streamline communication between users and our core team. We are confident that these changes will enhance efficiency and productivity in our development process.
