### ISSUE TITLE
Align Keycloak endpoints to recommendation

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#21]
https://www.keycloak.org/server/reverseproxy#_exposed_path_recommendations

Lets expose only recommended endpoints for Keycloak.

Acceptance Criteria:
- EDP scripts and documentation provides only recommended Keycloak endpoints out of the box for better security;

**Comment by alezander86** [comment]
By including these parameters in your values.yaml file, you configure Keycloak to follow the recommended endpoint settings. The console.enabled: false parameter disables the Keycloak console endpoint for better security. The exposeMetrics: false and exposeHealth: false parameters disable the metrics and health check endpoints, respectively, to eliminate unnecessary attack vectors.

```
health:
  enabled: false
metrics:
  enabled: false
ingress:
  console:
    enabled: false
```

For more information and additional configuration options, please refer to the documentation on [our website about the EDP project](https://epam.github.io/edp-install/operator-guide/install-keycloak/#keycloak-installation).
