### ISSUE TITLE
Add example of Parameter Store EDP secret creation

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#25]
EDP provide External Secret operator capabilities usage.

During EDP deployment user can provisioning EDP secrets by External Secret operator but in EDP documentation not present any examples of EDP secret structure.

Acceptance Criteria:

- mkdocs (https://epam.github.io/edp-install/) contain example of Parameter Store EDP secret creation;

**Comment by Rolika4** [comment]
We added a detailed description with [examples](https://epam.github.io/edp-install/operator-guide/external-secrets-operator-integration/#edp-install-scenario_1) of how users can create a secret in the AWS Parameter Store that can work with the External Secret operator in an EDP scenario. 

Also added a table with a description of each field and changed the steps for easier integration of EDP and External Secret operator.
