### ISSUE TITLE
 I can't see the github container registry settings

### ISSUE THREAD

**Issue by hugoarroyo** [epam/edp-install#256]
**Describe the bug**
I installed version 3.9.0 and I can't see the github container registry settings as per the documentation
https://epam.github.io/edp-install/user-guide/manage-container-registries/#__tabbed_1_6 

**To Reproduce**

#### What did you do?

I follow the instructions to install version 3.9.0
helm install edp epamedp/edp-install --version 3.9.0 --create-namespace --atomic -n edp --set global.dnsWildCard=example.com

#### What did you expect to see?
This tab enabled
![image](https://github.com/epam/edp-install/assets/13423055/56cc4b0b-5ba1-49e5-8d9f-84650c6e910f)

#### What did you see instead? Under which circumstances?
I don't see the option for github
![image](https://github.com/epam/edp-install/assets/13423055/304c0363-134e-4224-a4df-f0bde2f2499a)

**Kubernetes cluster type:**
Amazon Elastic Kubernetes 
Version 1.29

**Comment by NikolayMarusenko** [comment]
Have you tried clearing the cache and doing a hard reload of the page? Also, could you check the version of the edp-headlamp image you have deployed?
