### ISSUE TITLE
Use ct-config files from project root directory for helm applications

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#28]
Acceptance Criteria:

- EDP user can put ct-configs to root directory of repository and EDP uses these configs;
- enable helm-docs as mandatory component;

**Comment by Artem-Zahumonnyi** [comment]
## Update "helm-lint" Tekton Task.
We have recently implemented the ability to use custom configuration files for ct-lint tool in the "helm-lint" Tekton Task.
This allows the user to use his own ct.yaml, lintconf.yaml and chart_schema.yaml files by storing them in the root of the repository.

ct.yaml, lintconf.yaml and chart_schema.yaml files provided by the EDP command are used by default.

## New "helm-docs" Tekton Task.
Also, we have added a new Tekton Task. 
The new Tekton Task is named "helm-docs" and is available in the following templates:   
- Helm (Helm) - application template.
- Helm (Pipelines) - library template.

The task allows you to check if the README.md file exists in folders with helm templates and task checks its relevance.
The User can also use his own README.md.gotmpl file to create the required file structure.

"helm-docs" tool helps the user build documentation based on a values.yaml file from his helm template repository.

![Image](https://github.com/epam/edp-install/assets/51204821/9cf8a452-2f22-4b11-8a46-8fa71b8d8baf)

You can find the updated EDP template repositories at these links:
- https://github.com/epmd-edp/helm-helm-helm
- https://github.com/epmd-edp/helm-helm-pipeline
