### ISSUE TITLE
As an EDP user I want to have opportunity use Harbor as image registry

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#29]
Acceptance Criteria:

* EDP can be integrated with Harbor;
* [mkdocs](https://epam.github.io/edp-install) describes steps to deploy and integrate EDP with Harbor;
* EDP use Harbor to push and pull images (as base platform image registry);
* integrate with OIDC;
* check deploy and integration on OKD cluster;

**Comment by Artem-Zahumonnyi** [comment]
We have implemented the ability to use Harbor registry in the EDP Tekton pipelines.

This allows the user to push his container images in the Tekton CI pipelines to the Harbor registry.

The user can use our following articles to install Harbor, configure OIDC in it and integrate Harbor with EDP pipelines:
- [Install Harbor
](https://epam.github.io/edp-install/operator-guide/install-harbor/)
- [ Harbor OIDC Configuration](https://epam.github.io/edp-install/operator-guide/harbor-oidc/)
- [Integrate Harbor With EDP Pipelines](https://epam.github.io/edp-install/operator-guide/container-registry-harbor-integration-tekton-ci/)

We have also prepared [add-ons](https://github.com/epam/edp-cluster-add-ons) that allow user to deploy the Harbor in two different modes: ["Harbor without High Availability"](https://github.com/epam/edp-cluster-add-ons/tree/main/add-ons/harbor) and ["Harbor with High Availability"](https://github.com/epam/edp-cluster-add-ons/tree/main/add-ons/harbor-ha).
