### ISSUE TITLE
Describe how to upgrade EDP to 3.2.x version

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#3]
Acceptance Criteria:

- mkdocs contain article of how to install upgrade for EDP to 3.2.1 version (use example https://epam.github.io/edp-install/operator-guide/upgrade-edp-3.1/);
- verify documentation and all manual actions during upgrade procedure;

**Comment by SergK** [comment]
There is a fix #8 that was released in 3.2.2, so formally upgrading to 3.2.2

**Comment by YevheniiPokhvalii** [comment]
Closes: https://github.com/epam/edp-install/issues/8
