### ISSUE TITLE
Implement tekton cache usage

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#31]
Acceptance Criteria:

- customer can deploy EDP in multi AZ mode;
- pipelines can run in parallel;
- customer can scale cache size;

Possible approach:
https://github.com/actions/cache
https://aws.amazon.com/blogs/containers/using-amazon-ebs-snapshots-for-persistent-storage-with-your-amazon-eks-cluster-by-leveraging-add-ons/
https://aws.amazon.com/blogs/containers/using-ebs-snapshots-for-persistent-storage-with-your-eks-cluster/

Technical side:

We need to have flag to support other then aws deployment
Use aws ebs snapshoter https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/examples/kubernetes/snapshot/README.md

**Comment by SergK** [comment]
The cache is implemented for a cloud-agnostic approach see epam/edp-tekton for details
