### ISSUE TITLE
As a EDP User, I want to have capability to support for Doc as Code approach

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#38]
Type: Application
Framework: Antora
BuildTool: asciidoc

Add CI/CD pipelines for GitHub/GitLab/Gerrit

- We can use Npm react as a baseline
- Use dockerfile:

```
FROM nginxinc/nginx-unprivileged:1.23-alpine
COPY build/site/ /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
```

**Comment by Rolika4** [comment]
Now users can onboard a new application type - Antora. Antora- the multi-repository documentation site generator for tech writers who write in AsciiDoc.

Example of repository structure - https://github.com/epmd-edp/javascript-npm-antora. EDP users can easily onboard Antora Docs using the Headlamp UI. This new feature will be included in the upcoming release.

<img width="951" alt="Screenshot 2023-07-14 at 15 13 52" src="https://github.com/epam/edp-install/assets/52344283/d5c82cf4-23fe-4ab8-afb1-8fdb1b703a07">

<img width="1777" alt="Screenshot 2023-07-14 at 15 23 24" src="https://github.com/epam/edp-install/assets/52344283/77c1d949-fedc-4847-9694-297edf4be43f">
