### ISSUE TITLE
Describe marketplace section

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#42]
EDP Headlamp has new section - Marketplace.

Please create initial page in [mkdocs](https://epam.github.io/edp-install/) to describe main capabilities of Marketplace page.

**Acceptance Criteria:**

- [mkdocs](https://epam.github.io/edp-install/) contain article with main capabilities of Marketplace page;

**Comment by Oleksandr123234** [comment]
The Marketplace section has been added to the User Guide in mkdocs. It describes the purpose, features and usage of EDP Marketplace. To see the new documentation, use the [link](https://epam.github.io/edp-install/headlamp-user-guide/marketplace/).
