### ISSUE TITLE
Create EDP component argocd if integration enabled

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#46]
Acceptance Criteria:

* edp-install automatically create EDP component with valid link and icon in case if argocd integration enabled;

**Comment by alezander86** [comment]
Now, [Argocd EDP component](https://github.com/epam/edp-install/blob/master/deploy-templates/templates/argocd/edpcomponent.yaml) is created automatically. To enable it, you have to activate a parameter in [values](https://github.com/epam/edp-install/blob/master/deploy-templates/values.yaml#L48) during EDP installation and your Argocd will be displayed in Headlamp.


![Image](https://github.com/epam/edp-install/assets/77995538/5fa089f6-297c-48c1-aa78-e4e624635522)
