### ISSUE TITLE
Describe how to Delete EDP from cluster

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#5]
Add article to describe how user can delete EDP with all integrations and related resources (clean Keycloak, remove finalizers....).

Provide script to automate this process.

Acceptance Criteria:

- mkdocs (https://epam.github.io/edp-install/) contains article of how to delete (redeploy) EDP;
- provide script to remove finalizers in case if Namespace stuck in terminating state;
- describe how remove finalizers in manually mode;

**Comment by Oleksandr123234** [comment]
The "Uninstall EDP" page has been added. Please refer to the [link](https://epam.github.io/edp-install/operator-guide/delete-edp/) for details.
