### ISSUE TITLE
Describe auto deploy in Headlamp and Argo CD

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#6]
Acceptance Criteria:

- mkdocs contain article of how to use auto deploy in most cases;
- describe in business case (not only technical side);

**Comment by Oleksandr123234** [comment]
Autodeploy logic description has been provided in the [arch.md](https://github.com/epam/edp-cd-pipeline-operator/blob/master/docs/arch.md) file in the [edp-cd-pipeline-operator](https://github.com/epam/edp-cd-pipeline-operator/tree/master) repository.
