### ISSUE TITLE
Describe Jira integration functionality

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#7]
https://epam.github.io/edp-install/operator-guide/jira-integration/?h=jira

Currently, we need to provide detailed information on how to use Jira integration from a business and technical perspective.

Now use can use commit message validate even if Jira integration is disabled.
The Tekton jira integration step is optional, and we need to describe this in the documentation and explain how to enable this function.

Acceptance Criteria:

- mkdocs Jira article updated;
- use Headlamp UI instead of Admin Console;
- User can use the **commit-validate** Tekton step and know hot to enable this step;
- Documentation up-to-date of the latest Jira integration functional;
- The description style is not only technical but also business, to understand why this approach

**Comment by Oleksandr123234** [comment]
The [Adjust Jira Integration](https://epam.github.io/edp-install/operator-guide/jira-integration/) page has been updated to include the bullet points mentioned above. The relevant information has been added and is now available on the page.
