### ISSUE TITLE
Align VCS secret name pattern

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#77]
Acceptance Criteria:

- secret name - ci-gitlab/github;
- gerrit - without modification;

**Comment by Serg1506** [comment]
![Screenshot_12](https://github.com/epam/edp-install/assets/23012062/03746b25-ff40-4363-966b-7e2d67ebff54)
![Screenshot_11](https://github.com/epam/edp-install/assets/23012062/e2aece5b-718b-48c1-92d1-4bd7e90ce5e7)
