### ISSUE TITLE
Re-trigger pipeline for specific comment in GitHub/GitLab/Gerrit

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-install#9]
The current functionality of the platform does not allow a simple way to restart the pipeline review if necessary.
Add functionality that allows you to provoke the launch of a pipeline review with a specific comment in a merge request review

Acceptance Criteria:

- EDP user can trigger code review pipeline in manually mode;
- comment '/recheck' in PR is the way that user can run code-review pipeline;

**Comment by zmotso** [comment]
We can use /recheck review comment in the Gerrit/GitHub/GitLab to start the pipeline.
![image](https://github.com/epam/edp-install/assets/10484729/eda4d1bb-310a-4b89-9962-6a52c0f33424)
